### ISSUE TITLE
Add formatter for .jsona files

### ISSUE THREAD

**Issue by agungroyat** [jsona/vscode-jsona-syntax#1]
VSCode version: 1.60.1
Theme: Light+ (default light)

### Description

It would be nice to also have a formatter for .jsona files from this extension. The behavior could be something like VSCode formatting .json files adhering to the space indentation config if we use the Format Document shortcut. For example, if my editor indentation is set using 2 spaces, the extension would format the file with a 2-spaced indentation.

### Code sample

```
{
    test1: { @describe("user login")
        req: {
            url: 'http://localhost:3000/login'
            method: 'post',
            body: {
                user: 'jason',
                pass: 'a123456,
            }
        },
        res: {
            status: 200
            body: {
                user: 'jason',
                token: '', @type
                expireIn: 0, @type
            }
        }
    }
}
```

### Screenshot

![jsona-file](https://user-images.githubusercontent.com/13929765/134306540-7e07aa0f-4e3c-48c5-914b-cce664dbee2a.png)

**Comment by sigoden** [comment]
see https://github.com/jsona/vscode-jsona
